package com.meera.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.meera.db.model.BankOrganization;
import com.meera.db.service.BankOrganizationLocalServiceUtil;

/**
 * The extended model base implementation for the BankOrganization service. Represents a row in the &quot;Employees_BankOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankOrganizationImpl}.
 * </p>
 *
 * @author LiferaySavvy
 * @see BankOrganizationImpl
 * @see com.meera.db.model.BankOrganization
 * @generated
 */
public abstract class BankOrganizationBaseImpl extends BankOrganizationModelImpl
    implements BankOrganization {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bank organization model instance should use the {@link BankOrganization} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BankOrganizationLocalServiceUtil.addBankOrganization(this);
        } else {
            BankOrganizationLocalServiceUtil.updateBankOrganization(this);
        }
    }
}
