package com.meera.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.meera.db.model.JobDirectory;
import com.meera.db.service.JobDirectoryLocalServiceUtil;

/**
 * The extended model base implementation for the JobDirectory service. Represents a row in the &quot;Employees_JobDirectory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JobDirectoryImpl}.
 * </p>
 *
 * @author LiferaySavvy
 * @see JobDirectoryImpl
 * @see com.meera.db.model.JobDirectory
 * @generated
 */
public abstract class JobDirectoryBaseImpl extends JobDirectoryModelImpl
    implements JobDirectory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a job directory model instance should use the {@link JobDirectory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            JobDirectoryLocalServiceUtil.addJobDirectory(this);
        } else {
            JobDirectoryLocalServiceUtil.updateJobDirectory(this);
        }
    }
}
