package com.meera.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BankOrganization service. Represents a row in the &quot;Employees_BankOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.db.model.impl.BankOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.db.model.impl.BankOrganizationImpl}.
 * </p>
 *
 * @author LiferaySavvy
 * @see BankOrganization
 * @see com.meera.db.model.impl.BankOrganizationImpl
 * @see com.meera.db.model.impl.BankOrganizationModelImpl
 * @generated
 */
public interface BankOrganizationModel extends BaseModel<BankOrganization> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a bank organization model instance should use the {@link BankOrganization} interface instead.
     */

    /**
     * Returns the primary key of this bank organization.
     *
     * @return the primary key of this bank organization
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this bank organization.
     *
     * @param primaryKey the primary key of this bank organization
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the bank organization ID of this bank organization.
     *
     * @return the bank organization ID of this bank organization
     */
    public long getBankOrganizationId();

    /**
     * Sets the bank organization ID of this bank organization.
     *
     * @param bankOrganizationId the bank organization ID of this bank organization
     */
    public void setBankOrganizationId(long bankOrganizationId);

    /**
     * Returns the name of this bank organization.
     *
     * @return the name of this bank organization
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this bank organization.
     *
     * @param name the name of this bank organization
     */
    public void setName(String name);

    /**
     * Returns the b i k of this bank organization.
     *
     * @return the b i k of this bank organization
     */
    @AutoEscape
    public String getBIK();

    /**
     * Sets the b i k of this bank organization.
     *
     * @param BIK the b i k of this bank organization
     */
    public void setBIK(String BIK);

    /**
     * Returns the adress of this bank organization.
     *
     * @return the adress of this bank organization
     */
    @AutoEscape
    public String getAdress();

    /**
     * Sets the adress of this bank organization.
     *
     * @param adress the adress of this bank organization
     */
    public void setAdress(String adress);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.meera.db.model.BankOrganization bankOrganization);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.meera.db.model.BankOrganization> toCacheModel();

    @Override
    public com.meera.db.model.BankOrganization toEscapedModel();

    @Override
    public com.meera.db.model.BankOrganization toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
