package com.meera.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the JobDirectory service. Represents a row in the &quot;Employees_JobDirectory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.db.model.impl.JobDirectoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.db.model.impl.JobDirectoryImpl}.
 * </p>
 *
 * @author LiferaySavvy
 * @see JobDirectory
 * @see com.meera.db.model.impl.JobDirectoryImpl
 * @see com.meera.db.model.impl.JobDirectoryModelImpl
 * @generated
 */
public interface JobDirectoryModel extends BaseModel<JobDirectory> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a job directory model instance should use the {@link JobDirectory} interface instead.
     */

    /**
     * Returns the primary key of this job directory.
     *
     * @return the primary key of this job directory
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this job directory.
     *
     * @param primaryKey the primary key of this job directory
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the job directory ID of this job directory.
     *
     * @return the job directory ID of this job directory
     */
    public long getJobDirectoryId();

    /**
     * Sets the job directory ID of this job directory.
     *
     * @param jobDirectoryId the job directory ID of this job directory
     */
    public void setJobDirectoryId(long jobDirectoryId);

    /**
     * Returns the name of this job directory.
     *
     * @return the name of this job directory
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this job directory.
     *
     * @param name the name of this job directory
     */
    public void setName(String name);

    /**
     * Returns the archive status of this job directory.
     *
     * @return the archive status of this job directory
     */
    @AutoEscape
    public String getArchiveStatus();

    /**
     * Sets the archive status of this job directory.
     *
     * @param archiveStatus the archive status of this job directory
     */
    public void setArchiveStatus(String archiveStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.meera.db.model.JobDirectory jobDirectory);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.meera.db.model.JobDirectory> toCacheModel();

    @Override
    public com.meera.db.model.JobDirectory toEscapedModel();

    @Override
    public com.meera.db.model.JobDirectory toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
